services:
  app:
    image: cosmtrek/air
    depends_on:
      - redis
      - db
    volumes:
      - ./:/app
    ports: 
      - "8080:8080"
      - "8090:8090"
    links:
      - db
    environment:
      air_wd: /app

  db:
    image: postgres:16.6-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_COMMAND: createdb ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
