app = 'short-l8f-ew'
primary_region = 'syd'

[build]
  [build.args]
    GO_VERSION = '1.23.3'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[processes]
  web = "run-app"
  cron = "supercronic /etc/cron.d/app-tasks"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
